resultsdb_frontend/controllers/admin.py
# Copyright 2013, Red Hat, Inc
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Authors:
#   Josef Skladanka <jskladan@redhat.com>

from flask import Blueprint, render_template, flash, url_for
from flask.ext.login import login_required


admin = Blueprint('admin', __name__)

@admin.route('/admin')
@admin.route('/admin/')
@login_required
def admin_index():
    return render_template('admin/index.html')

resultsdb_frontend/controllers/main.py
# Copyright 2013, Red Hat, Inc
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Authors:
#   Josef Skladanka <jskladan@redhat.com>

from flask import Blueprint, render_template, redirect, url_for, request
from resultsdb_frontend import app

from resultsdb_api import ResultsDBapi

RDB_URL = 'http://localhost:5000/api/v1.0'
rdb_api = None


main = Blueprint('main', __name__)

@app.before_first_request
def before_first_request():
    global rdb_api
    rdb_api = ResultsDBapi(RDB_URL)

@main.route('/')
@main.route('/index')
def index():
     return redirect(url_for('main.jobs'))

@main.route('/jobs')
def jobs():
    jobs = rdb_api.get_jobs(**dict(request.args))
    return render_template('jobs.html', jobs = jobs)

@main.route('/jobs/<job_id>')
def job(job_id):
    job = rdb_api.get_job(id = job_id)
    jobs = dict(prev = None, next = None, data = [job])
    return render_template('jobs.html', jobs = jobs)

@main.route('/results')
def results():
    args = dict(request.args)
    if 'job_id' in args:
        args['job_id'] = request.args['job_id']
    results = rdb_api.get_results(**args)
    return render_template('results.html', results = results)

@main.route('/results/<result_id>')
def result(result_id):
    result = rdb_api.get_result(id = result_id)
    return render_template('result_detail.html', result = result)

@main.route('/testcases')
def testcases():
    args = dict(request.args)
    tcs = rdb_api.get_testcases(**args)
    return render_template('testcases.html', testcases = tcs)

@main.route('/testcases/<testcase_name>')
def testcase(testcase_name):
    tc = rdb_api.get_testcase(name = testcase_name)
    tcs = dict(prev = None, next = None, data = [tc])
    return render_template('testcases.html', testcases = tcs)

resultsdb_frontend/templates/_formhelpers.html
<!-- inspired by https://gist.github.com/maximebf/3986659 -->
{% macro form_field(field) %}
    {% set with_label = kwargs.pop('with_label', False) %}

    {% set inline_ = '' %}
    {% if field.type  == 'BooleanField' %}
        <div class="checkbox">
          <label>
            {{ field(**kwargs) }}
            {{ field.label.text|safe }}
          </label>
        </div>


    {% elif field.type == 'RadioField' %}
      {% for subfield in field %}
        <div class="radio">
          <label>
            {{ subfield(**kwargs) }}
            {{ subfield.label.text|safe }}
          </label>
        </div>
      {% endfor %}
    {% else %}
        <div class="form-group {% if field.errors %}has-error{% endif %}">
            {% set placeholder = '' %}
            {% if not with_label %}
                {% set placeholder = field.label.text %}
            {% endif %}

            {% if with_label %}
                <label for="{{ field.id }}">
                    {{ field.label.text }}{% if field.flags.required %} *{% endif %}:
                </label>
            {% endif %}

            {% set class_ = 'form-control' %}
            {% if field.type == 'FileField' %}
                {% set class_ = class_ + ' input-file' %}
            {% endif %}

            {{ field(class_=class_, placeholder=placeholder, **kwargs) }}

            {% if field.errors %}
                <span class="help-block">{{ field.errors|join(', ') }}</span>
            {% endif %}

            {% if field.description %}
                <p class="help-block">{{ field.description|safe }}</p>
            {% endif %}
        </div>
    {% endif %}
{% endmacro %}

resultsdb_frontend/templates/index.html
{% extends "layout.html" %}

{% block body %}

<h1>Welcome to resultsdb_frontend!</h1>

<p>
This is super-awesome page for the Flask Project. You can try logging in (admin/admin), or accessing the  <a href="{{ url_for('admin.admin_index') }}">Admin interface</a>.
</p>

{% endblock %}

resultsdb_frontend/templates/jobs.html
{% extends "layout.html" %}

{% block body %}
<table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Start time (UTC)</th>
        <th>Name</th>
        <th>Results</th>
        <th>Taskbot URL</th>
      </tr>
    </thead>
    <tbody>
    {% for job in jobs.data %}
      <tr>
        <td>{{ job.id }}</td>
        <td>{{ job.start_time | replace("T", " ")}}</td>
        <td>{{ job.name }}</td>
        <td><a href="{{ url_for('main.results', job_id = job.id) }}">{{ job.results_count }} results</a></td>
        <td><a href="{{ job.ref_url }}">Ref &rarr;</a></td>
      </tr>
    {% endfor %}
    </tbody>
</table>


<ul class="pager">
  {% if jobs.prev %}
    <li class="previous"><a href="{{ url_for('main.jobs') }}?{{ jobs.prev.split('?')[-1] }}">&larr; Newer Jobs</a></li>
  {% endif %}
  {% if jobs.next %}
    <li class="next"><a href="{{ url_for('main.jobs') }}?{{ jobs.next.split('?')[-1] }}">Older Jobs &rarr;</a></li>
  {% endif %}
</ul>


{% endblock %}

resultsdb_frontend/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>{{ title|default('resultsdb_frontend') }}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- Bootstrap -->
      <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
  </head>

  <body>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="navbar-brand"><b>resultsdb_frontend</b></span>
        </div>
        <div class="navbar-collapse collapse">

          <ul class="nav navbar-nav">
              <li><a href="{{ url_for('main.jobs') }}">Jobs</a></li>
              <li><a href="{{ url_for('main.results') }}">Results</a></li>
              <li><a href="{{ url_for('main.testcases') }}">Testcases</a></li>
          </ul>

<!--         <div class="navbar-right">
             <input type="button" class="btn btn-default navbar-btn" value="Search" onclick="location.href='';">
         </div> -->

        </div><!--/.nav-collapse -->
      </div><!--/.container -->
    </div><!--/.navbar -->


    <div class="container">
    {% for message in get_flashed_messages() %}
      <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}
    </div>



    <div class="container">
    {% block body %}
       <h1> My First Flask Application! </h1>
    {% endblock %}
    </div>



    {% block footer %}
    {% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  </body>
</html>

resultsdb_frontend/templates/login.html
{% extends "layout.html" %}

{% from "_formhelpers.html" import form_field %}

{% block body %}

<div class="row">
<div class="col-md-4">
<form method="post" action="login">
    {{ form.csrf_token }}
    {{ form.next_page }}
    {{ form_field(form.username) }}
    {{ form_field(form.password) }}
    <input type="submit" class="btn btn-success" value="Login"/>
</form>
</div>
</div>

{% endblock %}

resultsdb_frontend/templates/result_detail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">
    <div class="col-md-2"><strong>ID</strong></div>
    <div class="col-md-9">{{ result.id }}</div>
</div>
<div class="row">
    <div class="col-md-2"><strong>Submit time</strong></div>
    <div class="col-md-9">{{ result.submit_time | replace("T", " ")}}</div>
</div>
<div class="row">
    <div class="col-md-2"><strong>Testcase</strong></div>
    <div class="col-md-9"><a href="{{ url_for('main.testcase', testcase_name=result.testcase.href.split('/')[-1]) }}">{{ result.testcase.name }}</a></div>
</div>
<div class="row">
    <div class="col-md-2"><strong>Outcome</strong></div>
    <div class="col-md-9">{{ result.outcome }}</div>
</div>
<div class="row">
    <div class="col-md-2"><strong>Summary</strong></div>
    <div class="col-md-9">{{ result.summary }}</div>
</div>
<div class="row">
    <div class="col-md-2"><strong>Job</strong></div>
    <div class="col-md-9"><a href="{{ url_for('main.job', job_id=result.job_url.split('/')[-1]) }}">Job</a></div>
</div>
<div class="row">
    <div class="col-md-12">&nbsp;</div>
</div>

{% for key in result.result_data %}
<div class="row">
    <div class="col-md-2"><strong>{{key}}</strong></div>
    <div class="col-md-9">{{', '.join(result.result_data[key])}}</div>
</div>
{% endfor %}


{% endblock %}

resultsdb_frontend/templates/results.html
{% extends "layout.html" %}

{% block body %}
<table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Submit time (UTC)</th>
        <th>Testcase</th>
        <th>Outcome</th>
        <th>Summary</th>
        <th>Details</th>
        <th>Job</th>
        <th>Log</th>
      </tr>
    </thead>
    <tbody>
    {% for result in results.data %}
      <tr>
        <td>{{ result.id }}</td>
        <td>{{ result.submit_time | replace("T", " ")}}</td>
        <td><a href="{{ url_for('main.testcase', testcase_name=result.testcase.href.split('/')[-1]) }}">{{ result.testcase.name }}</a></td>
        <td>{{ result.outcome }}</td>
        <td>{{ result.summary }}</td>
        <td><a href="{{ url_for('main.result', result_id=result.id) }}">Details</a></td>
        <td><a href="{{ url_for('main.job', job_id=result.job_url.split('/')[-1]) }}">Job</a></td>
        <td><a href="{{ result.log_url }}">Log &rarr;</a></td>
      </tr>
    {% endfor %}
    </tbody>
</table>

<ul class="pager">
  {% if results.prev %}
    <li class="previous"><a href="{{ url_for('main.results') }}?{{ results.prev.split('?')[-1] }}">&larr; Newer Results</a></li>
  {% endif %}
  {% if results.next %}
    <li class="next"><a href="{{ url_for('main.results') }}?{{ results.next.split('?')[-1] }}">Older Results &rarr;</a></li>
  {% endif %}
</ul>



{% endblock %}

resultsdb_frontend/templates/testcases.html
{% extends "layout.html" %}

{% block body %}
<table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Results</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
    {% for testcase in testcases.data %}
      <tr>
        <td>{{ testcase.name }}</td>
        <td><a href="{{ url_for('main.results', testcase_name = testcase.name) }}">Results</a></td>
        <td><a href="{{ testcase.url }}">Ref &rarr;</a></td>
      </tr>
    {% endfor %}
    </tbody>
</table>


<ul class="pager">
  {% if testcases.prev %}
    <li class="previous"><a href="{{ url_for('main.testcases') }}?{{ testcases.prev.split('?')[-1] }}">&larr; Previous</a></li>
  {% endif %}
  {% if testcases.next %}
    <li class="next"><a href="{{ url_for('main.testcases') }}?{{ testcases.next.split('?')[-1] }}">Next &rarr;</a></li>
  {% endif %}
</ul>


{% endblock %}